name: Build container
on: [push]
jobs:
  Build-Container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y buildah
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: buildah login ghcr.io --password $GITHUB_TOKEN --username $GITHUB_REPOSITORY_OWNER
      - run: buildah images
      - run: buildah build -t sporad-server
      - run: buildah images
      - run: buildah push ghcr.io/SolidTux/sporad-server:latest
