name: Build container
on: [push]
jobs:
  Build-Container:
    runs-on: ubuntu-latest
    steps:
      - run: apt update
      - run: apt install -y buildah
      - run: buildah images
      - run: buildah build -t sporad-server
      - run: buildah images
      - run: buildah login -u ${GITHUB_REPOSITORY_OWNER} -p ${GITHUB_TOKEN} ghcr.io
      - run: buildah push server ghcr.io/SolidTux/sporad-server:latest
