name: Build container
on: [push]
jobs:
  Build-Container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y buildah
      - run: gh auth token | buildah login ghcr.io --username YOURUSER --password-stdin
      - run: buildah images
      - run: buildah build -t sporad-server
      - run: buildah images
      - run: buildah push server ghcr.io/SolidTux/sporad-server:latest
